spring.application.name=PvPEngine

spring.datasource.url=jdbc:postgresql://localhost:5433/pvpengine
spring.datasource.username=pvp
spring.datasource.password=pvpsecret

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true